/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 cone.gltf 
Author: Jackmcm (https://sketchfab.com/Jackmcm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/evil-cone-bd41ecc23835416bafea042d6a01a07b
Title: Evil Cone.
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cone(props) {
  const { nodes, materials } = useGLTF('/cone.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node_75684_Material_0_0.geometry} material={materials.Material_0} />
    </group>
  )
}

useGLTF.preload('/cone.gltf')
