/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 mountain.gltf 
Author: ill_drakon (https://sketchfab.com/ill_drakon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mountain-lake-3043ead27ac74144950e634197a1490b
Title: Mountain Lake
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mountain(props) {
  const { nodes, materials } = useGLTF('/mountain.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -10.996, 10.996]} rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.wm_meters_wm_meters0_0.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_1.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_2.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_3.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_4.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_5.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_6.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_7.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_8.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_9.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_10.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_11.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_12.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_13.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_14.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_15.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_16.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_17.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_18.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_19.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_20.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.wm_meters_wm_meters0_0_21.geometry} material={materials.wm_meters0} />
          <mesh geometry={nodes.PM3D_Cube3D1_PM3D_Cube3D10_0.geometry} material={materials.PM3D_Cube3D10} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mountain.gltf')
