/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 safe.gltf 
Author: François Espagnet (https://sketchfab.com/francoisespagnet)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/safety-temporary-fence-46bbfceb23ff435793d0b76628df0c2e
Title: Safety temporary fence
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Safe(props) {
  const { nodes, materials } = useGLTF('/safe.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/safe.gltf')
