/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 tree1.gltf 
Author: FelixBDesign (https://sketchfab.com/felix95b)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hazelnut-bush-8e8fd14f7f1546b9bcf2f5cfee5c116c
Title: Hazelnut Bush
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tree1(props) {
  const { nodes, materials } = useGLTF('/tree1.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['None_Hazelnut.png']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree1.gltf')
