/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 tunnel.gltf 
Author: Low poly 3d Models (https://sketchfab.com/lowpoly3dmodels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tunnel-road-9022ca0e48924aad96123389d5322a7d
Title: Tunnel Road
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tunnel(props) {
  const { nodes, materials } = useGLTF('/tunnel.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tunnel_2_tunnel_road_texture_0.geometry} material={materials.tunnel_road_texture} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/tunnel.gltf')
